#  Copyright (C) 2025 B3Partners B.V.
global:
  scrape_interval: '1m'

scrape_configs:
  - job_name: 'tailormap-api'
    scheme: 'http'
    basic_auth:
      password: '${ACTUATOR_PASSWORD}'
      username: '${ACTUATOR_USERNAME}'
    static_configs:
      - targets:
          - 'tailormap:8080'
    metrics_path: '/api/actuator/prometheus'
    # discard any metrics that are not related to Tailormap
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^tailormap_.*'
        action: keep
    # alternatively request only the metrics that are relevant from the actuator API
    #    params:
    #      includedNames:
    #        - 'tailormap_app_request,tailormap_applayer_switched_on'