CREATE DATABASE geodata;
GO
ALTER DATABASE geodata SET RECOVERY SIMPLE;
GO
USE geodata;
GO
CREATE LOGIN geodata WITH PASSWORD = '$(GEODATA_PASSWORD)';
GO
CREATE USER geodata FOR LOGIN geodata;
GO
ALTER SERVER ROLE sysadmin ADD MEMBER [geodata];
GO