-- oracle
CREATE TABLE pk_variation_uuid
(
    uuid_id   RAW(16)       DEFAULT SYS_GUID() PRIMARY KEY,
    file_name VARCHAR(255 CHAR),
    GEOM                   SDO_GEOMETRY
)
/

INSERT INTO pk_variation_uuid (file_name, geom)
VALUES ('parking', SDO_GEOMETRY('POINT(132959 457715)', 28992));
/

CREATE TABLE pk_variation_bigint
(
    bigint_id NUMBER(19) PRIMARY KEY,
    file_name VARCHAR(255 CHAR),
    GEOM                   SDO_GEOMETRY
)
/
INSERT INTO pk_variation_bigint (bigint_id, file_name, geom)
VALUES (1,'parking', SDO_GEOMETRY('POINT(132959 457715)', 28992));
/

CREATE TABLE pk_variation_serial
(
    serial_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255 CHAR),
    GEOM                   SDO_GEOMETRY
)
/
INSERT INTO pk_variation_serial (file_name, geom)
VALUES ('parking', SDO_GEOMETRY('POINT(132959 457715)', 28992));
/

CREATE TABLE pk_variation_integer
(
    integer_id INTEGER PRIMARY KEY,
    file_name  VARCHAR(255 CHAR),
    GEOM                   SDO_GEOMETRY
)
/
INSERT INTO pk_variation_integer (integer_id, file_name, geom)
VALUES (1,'parking', SDO_GEOMETRY('POINT(132959 457715)', 28992));
/

CREATE TABLE pk_variation_decimal
(
    decimal_id NUMBER(10,0) PRIMARY KEY,
    file_name  VARCHAR(255 CHAR),
    GEOM                   SDO_GEOMETRY
)
/
INSERT INTO pk_variation_decimal (decimal_id, file_name, geom)
VALUES (1,'parking', SDO_GEOMETRY('POINT(132959 457715)', 28992));
/

CREATE TABLE pk_variation_numeric
(
    numeric_id NUMBER(7,0) PRIMARY KEY,
    file_name  VARCHAR(255 CHAR),
    GEOM                   SDO_GEOMETRY
)
/
INSERT INTO pk_variation_numeric (numeric_id, file_name, geom)
VALUES (1,'parking', SDO_GEOMETRY('POINT(132959 457715)', 28992));
/
